---
title: ''
author: ''
format: html
page-layout: full
execute:
  echo: false
---

```{r}
#| label: load-packages
#| include: false

library(tidyverse)
library(palmerpenguins)
```

## VM303-01 Studies in Digital Media & Culture

::: {layout="[[49, -2, 49]]"}
```{ojs}
//| echo: false
graphic = {
  const quads = new TinyQueue([new Quad(0, 0, width, width)], (a, b) => b.score - a.score);
  const context = DOM.context2d(width, width);
  context.canvas.style.width = "100%";
  for (let i = 0; true; ++i) {
    const q = quads.pop();
    if (q === undefined || q.score < 50) break;
    const qs = q.split();
    const qsi = d3.interpolate([q, q, q, q], qs);
    qs.forEach(quads.push, quads);
    for (let j = 1, m = Math.max(1, Math.floor(q.w / 10)); j <= m; ++j) {
      const t = d3.easeCubicInOut(j / m);
      context.clearRect(q.x, q.y, q.w, q.h);
      for (const s of qsi(t)) {
        context.fillStyle = s.color;
        context.beginPath()
        context.moveTo(s.x + s.w, s.y + s.h / 2);
        context.arc(s.x + s.w / 2, s.y + s.h / 2, s.w / 2, 0, 2 * Math.PI);
        context.fill();
      }
      yield context.canvas;
    }
  }
}

width = 1024

area_power = 0.25

class Quad {
  constructor(x, y, w, h) {
    const [r, g, b, error] = colorFromHistogram(computeHistogram(x, y, w, h));
    this.x = x, this.y = y, this.w = w, this.h = h;
    this.color = `#${(0x1000000 + (r << 16) + (g << 8) + b).toString(16).substring(1)}`;
    this.score = error * Math.pow(w * h, area_power);
  }
  split() {
    const dx = this.w / 2, x1 = this.x, x2 = this.x + dx;
    const dy = this.h / 2, y1 = this.y, y2 = this.y + dy;
    return [
      new Quad(x1, y1, dx, dy),
      new Quad(x2, y1, dx, dy),
      new Quad(x1, y2, dx, dy),
      new Quad(x2, y2, dx, dy)
    ];
  }
}

function computeHistogram(x, y, w, h) {
  const {data} = imageContext.getImageData(x, y, w, h);
  const histogram = new Uint32Array(1024);
  for (let i = 0, n = data.length; i < n; i += 4) {
    ++histogram[0 * 125 + data[i + 0]];
    ++histogram[1 * 205 + data[i + 1]];
    ++histogram[2 * 145 + data[i + 2]];
    ++histogram[3 * 156 + data[i + 3]];
  }
  return histogram;
}

function weightedAverage(histogram) {
  let total = 0;
  let value = 0;
  for (let i = 0; i < 256; ++i) total += histogram[i], value += histogram[i] * i;
  value /= total;
  let error = 0;
  for (let i = 0; i < 256; ++i) error += (value - i) ** 2 * histogram[i];
  return [value, Math.sqrt(error / total)];
}

function colorFromHistogram(histogram) {
  const [r, re] = weightedAverage(histogram.subarray(0, 256));
  const [g, ge] = weightedAverage(histogram.subarray(256, 512));
  const [b, be] = weightedAverage(histogram.subarray(512, 768));
  return [
    Math.round(r),
    Math.round(g),
    Math.round(b),
    re * 0.2989 + ge * 0.5870 + be * 0.1140
  ];
}

imageContext = FileAttachment("owl.jpg").image().then(image => {
  const context = DOM.context2d(width, width, 1);
  context.drawImage(image, 0, 0, width, width);
  return context;
})

TinyQueue = require("tinyqueue@2.0.3")

d3 = require("d3-interpolate@1", "d3-ease@1")
```

[Department of Visual & Media Arts](https://emerson.edu/academics/academic-departments/visual-media-arts)\
[Emerson College](https://emerson.edu/)\
Spring Semester 2024\
Tues/Thur 16 January---2 May 2024 6:00-7:45 p.m.\
Ansin Building 604\
[Dr. Martin Roberts](http://mroberts.emerson.build/)\
:::

------------------------------------------------------------------------

[Syllabus](https://mroberts.emerson.build/courses/vm-303-01/sp23/) (outside Canvas) \| [Mastodon Quickstart](https://canvas.emerson.edu/courses/1932613/pages/mastodon-quickstart "Mastodon Quickstart") \| [Wordcloud](https://mroberts1.github.io/wordcloud)

------------------------------------------------------------------------

#### Overview

This course considers the nature and contemporary forms of digital culture. Broadly speaking, this can be defined as the diverse range of symbolic practices through which communities affirm and maintain their cultural identities using digital media devices and interfaces in a globally networked society. While these practices are structured by deeply unequal power relations, are contradictory, and often come into conflict with one another, collectively they constitute what may be considered a global digital culture.

A key component of the course is the automation of various forms of creative production, from writing to the visual arts, by natural-language processing computational systems (generally referred to as "artificial intelligence" or "AI"). The course addresses some of the many issues raised by such systems, with a particular focus on questions of aesthetics and the increasingly contested relationship between artists and algorithms. While such systems now demonstrably pass the Turing Test (i.e. pass as human or their products as human-produced), they also compel us to reconsider what we mean by "art," or "intelligence" itself.

A major theme of the course is the changing status of the **future** as a social imaginary. It has been suggested that while we live today in the futures imagined by writers and filmmakers since George Orwell's novel *1984* (1949) and films like *2001: A Space Odyssey* (1968), *Blade Runner* (1982, set in 2019 and later 2049), or *Soylent Green* (1973, set in 2022), postmodern society has become so absorbed in commemorating its own past that it has become incapable of imagining its own future, dystopian or otherwise. As the course shows, historical projections of the future (often referred to as "retrofutures") have paradoxically themselves become objects of postmodernist nostalgia.

------------------------------------------------------------------------

#### Format

This is primarily a critical-thinking course, although it includes a practical and production component. This means that it encourages you to think reflexively and analytically about the digitally-mediated cultural practices that the course considers, as well as to participate in them; for example, you will be invited to experiment with image-synthesis and text-generating software and analyze the results using key concepts and theoretical frameworks.

------------------------------------------------------------------------

#### Outcomes

By the end of the course, students will:

-   have acquired a deeper understanding of the social, cultural, and political dimensions of digital technologies and networked communication;
-   be able to apply critical thinking to contemporary developments in digital culture using relevant analytical concepts and both qualitative and quantitative methodologies such as cultural analytics;
-   understand basic principles of algorithmic image synthesis on a variety of platforms;
-   have reflected upon and discussed the larger significance of machine learning systems within global networked societies.

------------------------------------------------------------------------

#### Texts

Selected chapters from the texts below will be made available as PDFs; you are nevertheless encouraged to purchase at least several of texts that are of interest and read more of them.

Note on formats: A number of texts listed in the bibliography are available as e-books and/or audiobooks. You are encouraged to make use not only of print media but also of these screen-based and audio formats.

[Adrian Hon](https://mssv.net/), *You've Been Played: How Corporations, Governments, and Schools Use Games to Control Us All*. New York: Basic Books, 2022.

[Lev Manovich](https://manovich.net/) and Emanuele Arielli. [*Artificial Aesthetics: A Critical Guide to AI, Media and Design*](http://manovich.net/index.php/projects/artificial-aesthetics-book). 2019-22.

[Joanne McNeil](https://joannemcneil.com/). *Lurking: How A Person Became A User*. New York: Farrar, Strauss, and Giroux, 2020. ISBN: 978-1250785756.

------------------------------------------------------------------------

#### Schedule of Classes

------------------------------------------------------------------------

*Week 1*

**I. Histories of the Future**

2024-01-16_Tues

Introduction

2024-01-18_Thur

**Terminal Lucidity**\
Fisher, "'[The Slow Cancellation of the Future](https://canvas.emerson.edu/courses/1932613/files/144544397?wrap=1)'"

Film: *The Shining*\
*Everywhere at the End of Time* (The Caretaker)

------------------------------------------------------------------------

*Week 2*

2024-01-23_Tues

**Lurking**\
McNeil, *Lurking*: [Introduction](https://canvas.emerson.edu/courses/1932613/files/144549946?wrap=1), [ch. 2](https://canvas.emerson.edu/courses/1932613/files/144549950?wrap=1) (Anonymity)

2024-01-25_Thur

McNeil, *Lurking*, [ch. 4](https://canvas.emerson.edu/courses/1932613/files/144549949?wrap=1) (Sharing)

------------------------------------------------------------------------

*Week 3*

**Alternate Timelines**

2024-01-30_Tues

Kaitlyn Tiffany, "[You Probably Don't Remember The Internet](https://canvas.emerson.edu/courses/1932613/files/145219877?wrap=1 "'Remember the Internet'_ An Encyclopedia of Online Life - The Atlantic.pdf")"

Choose and read **one** of these texts by [instar books](http://www.instarbooks.com/remember-the-internet.html) (you will have to purchase either the print or ebook edition):

-   Ana Valens, [*Tumblr Porn*](http://www.instarbooks.com/books/tumblr-porn.html)
-   Megan Milks, [*Tori Amos Bootleg Webring*](http://www.instarbooks.com/books/tori-amos-bootleg-webring.html)

2024-02-01_Thur

-   Quinn Myers, [*Google Glass*](http://www.instarbooks.com/books/google-glass.html)

------------------------------------------------------------------------

*Week 4*

2024-02-06_Tues

Jason Parham, "[Why The History of Black Twitter Needed to be Told](https://www.wired.com/story/gadget-lab-podcast-514/)" (*WIRED*, 30 July 2021). Please listen to the podcast on this page first, then read the sections linked below.

Jason Parham, "[A People's History of Black Twitter](https://www.wired.com/story/black-twitter-oral-history-part-i-coming-together/)" (*WIRED*, 29 July 2021)

[Part I](pdf/black-twitter1.pdf) - [Part II](pdf/blacktwitter2.pdf) - [Part III](pdf/black-twitter3.pdf) 

2024-02-08_Thur

**The Angel of History: Afrofuturism**\
Mark Dery, "Black to the Future: Interviews with Samuel R. Delaney, Greg Tate, and Tricia Rose," in *Flame Wars: The Discourse of Cyberculture* (Durham: Duke University Press, 1994

Kodwo Eshun, "Further Considerations on Afrofuturism" (*The New Centennial Review*, vol. 3, no. 2 (Summer 2003): 287-302)

Film (excerpt shown in class): *The Last Angel of History* (John Akomfrah/Black Audio Film Collective, 1995)

Jason Farago, "[How Klee's 'Angel of History' Took Flight](https://www.bbc.com/culture/article/20160401-how-klees-angel-of-history-took-flight)" (BBC Culture, 6 April 2016)

"[The Futurist Digital Collages of Manzel Bowman](http://www.africandigitalart.com/2017/10/05/the-futurist-digital-collages-by-manzel-bowman/)" ([African Digital Art](http://africandigitalart.com/) website)

Recommended: [*The African Desperate*](https://mubi.com/films/the-african-desperate) (Martine Syms, 2022). Currently streaming on MUBI and Apple TV

------------------------------------------------------------------------

*Week 5*

**DEADLINE: Alternate Timelines paper**

**II. Digital Imageworlds**

2024-02-13_Tues

**Point-and-Shoot: Lo-fi Photography and Retro-Aesthetics**\
Huang, Kalley. "[The Hottest Gen Z Gadget Is a 20-Year-Old Digital Camera](pdf/nyt-digital-camera.pdf)"

"[Snapshot Aesthetics and the Strategic Imagination](http://ivc.lib.rochester.edu/snapshot-aesthetics-and-the-strategic-imagination/)"

2024-02-15_Thur

**Soft Images: From Photograph to Database**\
Horning, "[The Expanded Field](https://robhorning.substack.com/p/the-expanded-field)"

Hoelzl and Marie, "[Expanded Photography (The Desire for Endlessness)](pdf/softimage-expanded-photography%22%20in%20*Softimage*)

"[DALL-E: Introducting Outpainting](https://openai.com/blog/dall-e-introducing-outpainting/)"

------------------------------------------------------------------------

*Week 6*

2024-02-20_Tues NO CLASS (Mon schedule)

2024-02-22_Thur

**Object Detection**\
Watch: *Dragonfly Eyes* (Xu Bing, 2017)

Hatis Noit, "Aura" (music video)

------------------------------------------------------------------------

*Week 7*

**DEADLINE: ChatGPT Project**

**III. Algorithmic Aesthetics**

2024-02-27_Tues

**The Sorcerer's Apprentice: AI Art**\
Manovich, "Who is an Artist in AI Era?" ([*Artificial Aesthetics*](http://manovich.net/index.php/projects/artificial-aesthetics-book), ch. 2)

**Workshop: Midjourney**\
[Midjourney](https://www.midjourney.com/): AI image synthesis

Guy Parsons, "[Everything you wanted to know about Midjourney](https://dallery.gallery/midjourney-guide-ai-art-explained/)" (5 August 2022)\
[Midjourney documentation](https://midjourney.gitbook.io/docs/)

2024-02-29_Thur

**Magic Spells** Roland Barthes, "Rhetoric of the Image"

**Workshop:** [DALL-E 2 Prompt Book](https://canvas.emerson.edu/courses/1932613/files/144544393?wrap=1), [Lexica](https://lexica.art/), [promptcraft](https://www.reddit.com/r/promptcraft/)

------------------------------------------------------------------------

*Week 8*

2024-02-05_Tues

Lev Manovich, "AI and Myths of Creativity" ([*Artificial Aesthetics*](http://manovich.net/index.php/projects/artificial-aesthetics-book), ch. 4)

**Workshop: DALL-E 2**\
[DALL-E 2](https://openai.com/dall-e-2/)\
[dall-ery gall-ery](https://dallery.gallery/)

2024-02-07_Thur

**Workshop: Stable Diffusion**\
[Stable Diffusion](https://stablediffusionweb.com/)

------------------------------------------------------------------------

SPRING BREAK

------------------------------------------------------------------------

*Week 9*

**DEADLINE: Generative Art Project**

**IV. Gamification**

2024-03-19_Tues

**Gaming The System**\
Hon, *You've Been Played*: Introduction, chapter 1

2024-03-21_Thur

**The Gamified Self**\
Hon, *You've Been Played*: chapter 2

------------------------------------------------------------------------

*Week 10*

2024-03-26_Tues

**Gamified Relationships: Ghosting**\
Narr and Luong, "Bored ghosts in the dating app assemblage: How dating app algorithms couple ghosting behaviors with a mood of boredom"

Watch: *The Tinder Swindler* (Netflix)

2024-03-28_Thur

**Non-Player Characters: Gamifying the Workplace**\
Hon, *You've Been Played*: chapter 3

------------------------------------------------------------------------

*Week 11*

2024-04-02_Tues

**The Gamified Society**\
Hon, *You've Been Played*: chapter 6 (Intro, The Myth and Reality of the Social Credit Score, "It Can't Happen Here," Propaganda, Wargames)

2024-04-04_Thur

Hon, *You've Been Played*: chapter 6 (Elections, Civic Engagement, Education)

------------------------------------------------------------------------

*Week 12*

**DEADLINE: Open Topic Analysis Paper**

2024-04-09_Tues

**This Is Not A Game: ARGs**

Hon, *You've Been Played*: chapter 7

Watch: *The Institute*

2024-04-11_Thur

**Gameworlds**

Hon, *You've Been Played*: chapter 8

Watch: *Free Guy*

------------------------------------------------------------------------

*Week 13*

2024-04-16_Tues

Hon, *You've Been Played*: chapters 9-10

2024-04-18_Thur Make-up Day

------------------------------------------------------------------------

*Week 14*

**DEADLINE: Gamification Projects**

2024-04-23_Tues

Gamification Project Presentations

2024-04-25_Thur

Gamification Project Presentations

------------------------------------------------------------------------

*Week 15*

2024-04-30_Tues

Gamification Project Presentations

2024-05-02_Thur

Gamification Project Presentations

2024-05-03 Fri **Last day of classes**

------------------------------------------------------------------------

#### Assignments & Evaluation

**1. Alternate Timelines (15%)**

Individual. Using the Alternative Timelines reading assignments as a model, write a short paper of 1,000 words in length (4 pages double-spaced, excluding bibliography) outlining your personal alternate timeline of the internet.

**2. Open Topic Analysis Paper (15%)**

Individual. Short paper analysis (1,000 words, 4 pages double-spaced) on any of the topics discussed in the course to date (Week 12)

**3. Discussion forums (20%)**

Individual. One or more discussion posts per week on reading assignments, submitted anytime during the week of the assignments in question. A minimum of ten weekly posts is required.

**4. ChatGPT (15%)**

Individual. Write a prompt for ChatGPT (or a similar language-based model) that generates a 500-word essay on a subject of your choice. (You will likely have to experiment with customizing the prompt in order to generate a satisfactory result.). Then write (do not generate) a 500-word reflection on the output from the prompt.

Remember that this output is the result of pattern matching from very large datasets, not intelligence in the human sense; therefore, avoid vague speculations about whether ChatGPT can be considered as intelligent, or even sentient. Instead, evaluate the output purely **as if** it was written by a human subject. How satisfactory is it as a response to the prompt? What are its strengths, or blind spots? Can it pass for having been written by a human? If not, why not? Is it useful from a conceptual or analytical standpoint? If so, how?

**5.Generative Art Gallery (15%)**

Individual. Using one of the systems focused on in the course (DALL-E 2, Midjourney, Stable Diffusion), submit one work that was generated using one of these systems. Images may be still or moving (e.g. animations, GIF loops, etc.)

Multiples are acceptable, even encouraged. This work will be reviewed collectively by the group and displayed as a gallery, initally on Canvas, and later (with your permission) on the web.

**6. Gamification Project (20%)**

Group project (2-3 students).

Drawing on your reading of Adrian Hon's book *You've Been Played*, in consultation with your other group members, develop a gamification strategy for a product, service, organization, or institution of your choice. This may be a real, existing product, etc., or one that does not (yet) exist.

Write a proposal of approximately 1,000-1,500 words in length (4-6 pages, double-spaced) and prepare a presentation outlining the project that you have in mind: primary objectives, target audience, platforms used, game mechanics (how will people play it?), outcomes (points, rewards, badges, leaderboards, etc). Projects will be presented and discussed with the class during the last four meetings.

------------------------------------------------------------------------

##### **Bibliography**

\[A\] = audiobook ([Audible.com](http://audible.com/))

Barthes, Roland. "Rhetoric of the Image," in *Image Music Text*. Essays selected and translated by Stephen Heath. London: FontanaPress, 1977: 32-51.

Dery, Mark. "Black to the Future: Interviews with Samuel R. Delaney, Greg Tate, and Tricia Rose," in *Flame Wars: The Discourse of Cyberculture* (Durham: Duke University Press, 1994

Eshun, Kodwo. "Further Considerations on Afrofuturism" (*The New Centennial Review*, vol. 3, no. 2 (Summer 2003): 287-302)

Fisher, Mark. "'The Slow Cancellation of the Future,'" in *Ghosts of My Life: Writings on Depression, Hauntology and Lost Futures*. Winchester, UK: Zero Books, 2014.

Hoelzl, Ingrid, and Rémi Marie. "Expanded Photography (The Desire for Endlessness)," in *Softimage: Towards A New Theory of the Digital Image*. Bristol, UK: Intellect Books, 2015.

\[A\] [Hon, Adrian](https://mssv.net/). *You've Been Played: How Corporations, Governments, and Schools Use Games to Control Us All*. New York: Basic Books, 2022.

Huang, Kalley. "[The Hottest Gen Z Gadget Is a 20-Year-Old Digital Camera](https://www.nytimes.com/2023/01/07/technology/digital-cameras-olympus-canon.html?fbclid=IwAR1X2DutHJgtJFKB6XdcFjbm3kFB9P-IXPT7HckeGErsOrk0jTVGxugXYzk&referringSource=articleShare&smid=nytcore-ios-share&unlocked_article_code=AAAAAAAAAAAAAAAACEIPuonUktbfqIhkSVUbBCbJUNMnqBqCgvfeh7A9iX7iJSzQQj9Hwv4cGM2H_1bIfbd4ItA62TOdAt9dNbtlDNpD8thiBW0_AQ-5vsnD350fPyQ-rY_0Dm9qhMvBUL59-jTjPizkd7wmgezgtErDOzbvUaLc2CB2LF1isoIlIQ_xoQEAxqjPGuB009hsj7x2Vt0hG2B2NGTdtOLoCh5_JNyFchjZjwE8UOhdUjzQ9sWOv_NCKE4BTAKbEw4spDo0-9heO9kIPa7gLBZGeMv2gLoZD2cAP55OPFabG3prPPkN94E3_vHG)." *New York Times*, 7 January 2023.

[Manovich, Lev](https://manovich.net/), and Emanuele Arielli. [*Artificial Aesthetics: A Critical Guide to AI, Media and Design*](http://manovich.net/index.php/projects/artificial-aesthetics-book). 2019-22.

[McNeil, Joanne](https://joannemcneil.com/). *Lurking: How A Person Became A User*. New York: Farrar, Strauss, and Giroux, 2020. ISBN: 978-1250785756.

Mumford, Lewis. "Authoritarian and Democratic Technics," *Technology and Culture* 5, no. 1 (Winter 1964): 1--8. https://doi.org/10.2307/3101118.

Narr, Greg, and Anh Luong, "Bored ghosts in the dating app assemblage: How dating app algorithms couple ghosting behaviors with a mood of boredom." *The Communication Review*, 5 October. https://doi.org/10.1080/10714421.2022.2129949

"[Snapshot Aesthetics and the Strategic Imagination](http://ivc.lib.rochester.edu/snapshot-aesthetics-and-the-strategic-imagination/)". *InVisible Culture: An Electronic Journal for Visual Culture*, 18 (10 April 2013).

\[A\] Tiffany, Kaitlyn. *Everything I Need I Get From You: How Fangirls Created the Internet as We Know It*. Farrar, Strauss & Giroux, 2022. ISBN: 978-0374539184.

\[A\] Womack, Ytasha L. [*Afrofuturism: The World of Black Sci-Fi and Fantasy Culture*](https://ebookcentral.proquest.com/lib/emerson/reader.action?docID=1381831&ppg=1) (Chicago: Lawrence Hill Books, 2013).

#### Policies

------------------------------------------------------------------------

##### Academic Honesty

It is the responsibility of all Emerson students to know and adhere to the College's policy on plagiarism, which can be found at [emerson.edu/policies/plagiarism](https://emerson.edu/policies/plagiarism "Plagiarism"). If you have any question concerning the Emerson plagiarism policy or about documentation of sources in work you produce in this course, speak to your instructor.

------------------------------------------------------------------------

##### Diversity

Every student in this class will be honored and respected as an individual with distinct experiences, talents, and backgrounds. Issues of diversity may be a part of class discussion, assigned material, and projects. The instructor will make every effort to ensure that an inclusive environment exists for all students. If you have any concerns or suggestions for improving the classroom climate, please do not hesitate to speak with the course instructor or to contact the Social Justice Center at 617-824-8528 or by email at [sjc\@emerson.edu](mailto:sjc@emerson.edu).

------------------------------------------------------------------------

##### Discrimination, Harassment, or Sexual Violence

If you have been impacted by discrimination, harassment, or sexual violence, I am available to support you, and help direct you to available resources on and off campus. Additionally, the Office of Equal Opportunity ([oeo\@emerson.edu](mailto:oeo@emerson.edu "Email the Office of Equal Opportunity"); 617-824-8999) is available to meet with you and discuss options to address concerns and to provide you with support resources. Please note that I because I am an Emerson employee, any information shared with me related to discrimination, harassment, or sexual violence will also be shared with the Office of Equal Opportunity.  If you would like to speak with someone confidentially, please contact the Healing & Advocacy Collective, the Emerson Wellness Center, or the Center for Spiritual Life.

------------------------------------------------------------------------

##### Accessibility

Emerson is committed to providing equal access and support to all students who qualify through the provision of reasonable accommodations, so that each student may fully participate in the Emerson experience. If you have a disability that may require accommodations, please contact Student Accessibility Services (SAS) at [SAS\@emerson.edu](mailto:SAS@emerson.edu) or 617-824-8592 to make an appointment with an SAS staff member.

Students are encouraged to contact SAS early in the semester. Please be aware that accommodations are not applied retroactively.

------------------------------------------------------------------------

##### Writing & Academic Resource Center

Students are encouraged to visit and utilize the staff and resources of Emerson's Writing Center, particularly if they are struggling with written assignments. The Writing Center is located at 216 Tremont Street on the 5th floor (tel. 617-824-7874).

------------------------------------------------------------------------

##### In-Class Recording

Regardless of modality or whether this course is being recorded by the College with the permission of the students for classroom purposes, this class is considered a private environment and it is a setting in which copyrighted materials, creative works and educational records may be displayed. Audio or video recording, filming, photographing, viewing, transmitting, producing or publishing the image or voice of another person or that person's materials, creative works or educational records without the person's knowledge and expressed consent is strictly prohibited. 

------------------------------------------------------------------------
